name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.2.3)'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/embedding-generator-service

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push to GHCR
      id: build
      run: |
        # Extract version
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        
        # Build the image
        docker build -f Dockerfile.prod -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} .
        docker build -f Dockerfile.prod -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
        
        # Push the images
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        # Set outputs
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "MAJOR_MINOR=${VERSION%.*}" >> $GITHUB_OUTPUT
        echo "MAJOR=${VERSION%%.*}" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ steps.build.outputs.VERSION }}
        name: Release ${{ steps.build.outputs.VERSION }}
        body: |
          ## 🚀 Release ${{ steps.build.outputs.VERSION }}
          
          ### Docker Images
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.VERSION }}`
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.MAJOR_MINOR }}`
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.MAJOR }}`
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest`
          - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable`
          
          ### Usage
          ```bash
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.VERSION }}
          ```
        draft: false
        prerelease: false

    - name: Release notification
      run: |
        echo "🎉 Release ${{ steps.build.outputs.VERSION }} created successfully!"
        echo "📦 Docker images:"
        echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.VERSION }}"
        echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.MAJOR_MINOR }}"
        echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.MAJOR }}"
        echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable"
